### ISSUE TITLE
ConfigParser.NoSectionError: No section: 'suffix' with nsscache >= 0.36

### ISSUE THREAD

**Issue by jtdowney** [google/nsscache#85]
I am getting the following error just running `nsscache status` with 0.37. I went back to 0.35 and the error goes away. I did some digging and I believe it is related to the changes in 67fb7fd793d96ca688d7dd22d53733cde6766c34. I am not a python expert, but it appears this commit would only work if there is an nsscache.conf in the current directory. The later changes 9c7cb12bd01a2db0ef2a063e52c3af819a794dcc and efa45571212df6230acd8de725d76531f27bc184 handle the case where the config is specified with a command line flag and addes support for the default file location but that was removed in 4b01106378ef3631649462b85ce8d06dfcce7de9.

Am I missing something?

```
# nsscache status
Traceback (most recent call last):
  File "/usr/bin/nsscache", line 28, in <module>
    from nss_cache import app
  File "/usr/lib/python2.7/site-packages/nss_cache/app.py", line 34, in <module>
    from nss_cache import command
  File "/usr/lib/python2.7/site-packages/nss_cache/command.py", line 35, in <module>
    from nss_cache.caches import cache_factory
  File "/usr/lib/python2.7/site-packages/nss_cache/caches/cache_factory.py", line 28, in <module>
    from nss_cache.caches import files
  File "/usr/lib/python2.7/site-packages/nss_cache/caches/files.py", line 57, in <module>
    prefix = parser.get('suffix', 'prefix')
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'suffix'
```

**Comment by 3c2b2ff5** [comment]
This is fixed now after the migration to Python 3. Issue can be closed.
